# https://docs.docker.jp/compose/wordpress.html
# https://qiita.com/shikuno_dev/items/f236c8280bb745dd6fb4
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ${HOME}/data/web:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/data/db:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - ${HOME}/data/web:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - inception

networks:
  inception:
    driver: bridge
